import { Toy } from "@/types/toy";

export const DUMMY_TOYS: Toy[] = [
    {
        id: "1",
        title: "LEGO Star Wars Millennium Falcon",
        description: "Build the legendary Millennium Falcon with over 7,500 pieces. Perfect for any Star Wars fan.",
        price: 65000,
        type: "new",
        condition: "New",
        images: ["https://images.unsplash.com/photo-1585366119957-e9730b6d0f60?auto=format&fit=crop&q=80&w=800"],
        ownerId: "store1",
        sellerType: "Store",
        ageGroup: "16+",
        category: "Building Sets",
        rating: 4.9,
        reviewsCount: 128,
    },
    {
        id: "2",
        title: "Vintage Tonka Dump Truck",
        description: "Original metal Tonka truck from the 80s. Sturdy and still ready for the sandbox.",
        price: 2500,
        type: "used",
        condition: "Good",
        images: ["https://images.unsplash.com/photo-1594736797933-d0501ba2fe65?auto=format&fit=crop&q=80&w=800"],
        ownerId: "user1",
        sellerType: "Individual",
        ageGroup: "4-7",
        category: "Vehicles",
        rating: 4.5,
        reviewsCount: 12,
    },
    {
        id: "3",
        title: "Giant Inflatable Bouncy Castle",
        description: "Perfect for weekend birthday parties. Easy to set up and provides hours of fun.",
        price: 3000,
        rentalPricePerDay: 500,
        depositAmount: 2000,
        type: "rental",
        condition: "Good",
        images: ["https://images.unsplash.com/photo-1627582522770-f1c5c00e6191?auto=format&fit=crop&q=80&w=800"],
        ownerId: "user2",
        sellerType: "Individual",
        ageGroup: "4-12",
        category: "Outdoor",
        rating: 4.8,
        reviewsCount: 45,
    },
    {
        id: "4",
        title: "Fisher-Price Baby Playmat",
        description: "Soft and colorful playmat with overhead toys and music for tummy time.",
        price: 1500,
        type: "used",
        condition: "Like New",
        images: ["https://images.unsplash.com/photo-1515488764276-beab7607c1e6?auto=format&fit=crop&q=80&w=800"],
        ownerId: "user3",
        sellerType: "Individual",
        ageGroup: "0-3",
        category: "Baby Toys",
        rating: 4.7,
        reviewsCount: 22,
    },
];
