import { Toy } from "@/types/toy";

export const KEEDOS_POPULAR_PRODUCTS: Toy[] = [
    {
        id: "ninno",
        title: "NINNO",
        description: "3D Modular Toy Character",
        price: 210.99,
        rating: 5,
        type: "new",
        condition: "New",
        images: ["https://images.unsplash.com/photo-1596461404969-9ae70f2830c1"],
        ownerId: "owner1",
        sellerType: "Store",
        ageGroup: "5+",
        category: "Collectibles",
        reviewsCount: 12
    },
    {
        id: "hiai",
        title: "HI-AI",
        description: "3D Modular Toy Character",
        price: 128.19,
        rating: 5,
        type: "new",
        condition: "New",
        images: ["https://images.unsplash.com/photo-1596461404969-9ae70f2830c1"],
        ownerId: "owner1",
        sellerType: "Store",
        ageGroup: "5+",
        category: "Collectibles",
        reviewsCount: 24
    },
    {
        id: "vurina",
        title: "VURINA",
        description: "3D Modular Toy Character",
        price: 122.39,
        rating: 5,
        type: "new",
        condition: "New",
        images: ["https://images.unsplash.com/photo-1558679908-541bcf1249ff"],
        ownerId: "owner1",
        sellerType: "Store",
        ageGroup: "5+",
        category: "Collectibles",
        reviewsCount: 18
    },
    {
        id: "hitha",
        title: "HITHA",
        description: "3D Modular Toy Character",
        price: 120.49,
        rating: 5,
        type: "new",
        condition: "New",
        images: ["https://images.unsplash.com/photo-1596461404969-9ae70f2830c1"],
        ownerId: "owner1",
        sellerType: "Store",
        ageGroup: "5+",
        category: "Collectibles",
        reviewsCount: 15
    },
    {
        id: "heoni",
        title: "HEONI",
        description: "3D Modular Toy Character",
        price: 105.29,
        rating: 5,
        type: "new",
        condition: "New",
        images: ["https://images.unsplash.com/photo-1621252179027-94459d278660"],
        ownerId: "owner1",
        sellerType: "Store",
        ageGroup: "5+",
        category: "Collectibles",
        reviewsCount: 20
    },
    {
        id: "amai",
        title: "AMAI",
        description: "3D Modular Toy Character",
        price: 155.39,
        rating: 5,
        type: "new",
        condition: "New",
        images: ["https://images.unsplash.com/photo-1558679908-541bcf1249ff"],
        ownerId: "owner1",
        sellerType: "Store",
        ageGroup: "5+",
        category: "Collectibles",
        reviewsCount: 32
    },
];

export const KEEDOS_DEALS_PRODUCTS: Toy[] = [
    {
        id: "d1",
        title: "ROMBLER",
        description: "3D vinyl character - Orange monster.",
        price: 112.21,
        rating: 5,
        type: "new",
        condition: "New",
        images: ["https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?auto=format&fit=crop&q=80&w=800"],
        ownerId: "owner1",
        sellerType: "Store",
        ageGroup: "5+",
        category: "Collectibles",
        reviewsCount: 15
    },
    {
        id: "d2",
        title: "GULP",
        description: "3D vinyl character - Green plant boy.",
        price: 110.19,
        rating: 5,
        type: "new",
        condition: "New",
        images: ["https://images.unsplash.com/photo-1621252179027-94459d278660?auto=format&fit=crop&q=80&w=800"],
        ownerId: "owner1",
        sellerType: "Store",
        ageGroup: "5+",
        category: "Collectibles",
        reviewsCount: 32
    },
    {
        id: "d3",
        title: "VUNIBI",
        description: "3D vinyl character - Gray cat.",
        price: 108.29,
        rating: 5,
        type: "new",
        condition: "New",
        images: ["https://images.unsplash.com/photo-1558679908-541bcf1249ff?auto=format&fit=crop&q=80&w=800"],
        ownerId: "owner1",
        sellerType: "Store",
        ageGroup: "5+",
        category: "Collectibles",
        reviewsCount: 18
    },
    {
        id: "d4",
        title: "YANOBI",
        description: "3D vinyl character - Sproutling.",
        price: 111.77,
        rating: 5,
        type: "new",
        condition: "New",
        images: ["https://images.unsplash.com/photo-1587654780291-39c9404d746b?auto=format&fit=crop&q=80&w=800"],
        ownerId: "owner1",
        sellerType: "Store",
        ageGroup: "5+",
        category: "Collectibles",
        reviewsCount: 10
    },
];

export const FOR_YOUNGEST_PRODUCTS: Toy[] = [
    {
        id: "y1",
        title: "MEN SHENG",
        description: "Plushy bear toy.",
        price: 142.11,
        rating: 5,
        type: "new",
        condition: "New",
        images: ["/images/Gemini_Generated_Image_yqij0pyqij0pyqij.png"],
        ownerId: "owner1",
        sellerType: "Store",
        ageGroup: "1+",
        category: "Plush",
        reviewsCount: 50
    },
    {
        id: "y2",
        title: "RC CAR",
        description: "Plushy avocado toy.",
        price: 147.12,
        rating: 5,
        type: "new",
        condition: "New",
        images: ["/images/car.png"],
        ownerId: "owner1",
        sellerType: "Store",
        ageGroup: "1+",
        category: "Plush",
        reviewsCount: 30
    },
    {
        id: "y3",
        title: "ZHAOYUN",
        description: "Plushy dinosaur toy.",
        price: 110.19,
        rating: 5,
        type: "new",
        condition: "New",
        images: ["/images/Gemini_Generated_Image_wjz7gcwjz7gcwjz7.png"],
        ownerId: "owner1",
        sellerType: "Store",
        ageGroup: "1+",
        category: "Plush",
        reviewsCount: 40
    },
    {
        id: "y4",
        title: "HONG LING",
        description: "Plushy fox toy.",
        price: 116.75,
        rating: 5,
        type: "new",
        condition: "New",
        images: ["/images/Gemini_Generated_Image_f4qtvpf4qtvpf4qt.png"],
        ownerId: "owner1",
        sellerType: "Store",
        ageGroup: "1+",
        category: "Plush",
        reviewsCount: 45
    },
];
