import { Toy } from "@/types/toy";

export const KEEDOS_POPULAR_PRODUCTS: Toy[] = [
    {
        id: "toy1",
        title: "Wooden Train Set",
        description: "Complete set with tracks and bridge.",
        price: 799,
        rating: 5,
        type: "both",
        rentalPricePerDay: 49,
        condition: "Like New",
        images: ["/images/Gemini_Generated_Image_3ciibx3ciibx3cii.png"],
        ownerId: "owner1",
        sellerType: "Individual",
        ageGroup: "3+",
        category: "Building",
        reviewsCount: 12
    },
    {
        id: "toy2",
        title: "Stacking Sets",
        description: "Fire station set, missing box but all pieces included.",
        price: 1200,
        rating: 5,
        type: "sale",
        condition: "Good",
        images: ["/images/Gemini_Generated_Image_7k4mpa7k4mpa7k4m.png"],
        ownerId: "owner1",
        sellerType: "Individual",
        ageGroup: "5+",
        category: "Building",
        reviewsCount: 8
    },
    {
        id: "toy3",
        title: "Animal Sets 5pc",
        description: "Great condition magnetic tiles.",
        price: 0,
        rentalPricePerDay: 60,
        rating: 5,
        type: "rental",
        condition: "Used",
        images: ["/images/Gemini_Generated_Image_d33q5vd33q5vd33q.png"],
        ownerId: "owner1",
        sellerType: "Individual",
        ageGroup: "3+",
        category: "Building",
        reviewsCount: 24
    },
    {
        id: "toy4",
        title: "Tricycle",
        description: "Gently used, elevator works perfectly.",
        price: 2500,
        rentalPricePerDay: 150,
        rating: 5,
        type: "both",
        condition: "Good",
        images: ["/images/Gemini_Generated_Image_h6r7q2h6r7q2h6r7.png"],
        ownerId: "owner1",
        sellerType: "Individual",
        ageGroup: "4+",
        category: "Dolls",
        reviewsCount: 15
    },
    {
        id: "toy5",
        title: "Doll House",
        description: "Loop-the-loop set with 2 cars.",
        price: 500,
        rentalPricePerDay: 30,
        rating: 5,
        type: "rental",
        condition: "Like New",
        images: ["/images/Gemini_Generated_Image_mfwf7vmfwf7vmfwf.png"],
        ownerId: "owner1",
        sellerType: "Individual",
        ageGroup: "4+",
        category: "Vehicles",
        reviewsCount: 5
    },
    {
        id: "toy6",
        title: "Rocking Horse",
        description: "Battery operated, all keys working.",
        price: 450,
        rating: 5,
        type: "sale",
        condition: "Good",
        images: ["/images/Gemini_Generated_Image_7wjj8l7wjj8l7wjj.png"],
        ownerId: "owner1",
        sellerType: "Individual",
        ageGroup: "2+",
        category: "Musical",
        reviewsCount: 9
    },
];

export const KEEDOS_DEALS_PRODUCTS: Toy[] = [
    {
        id: "pop1",
        title: "Premium Lego Sets",
        description: "Perfect for toddlers learning shapes.",
        price: 850,
        rentalPricePerDay: 40,
        rating: 5,
        type: "both",
        condition: "Good",
        images: ["/images/Gemini_Generated_Image_la1z3pla1z3pla1z.png"],
        ownerId: "owner1",
        sellerType: "Individual",
        ageGroup: "1+",
        category: "Educational",
        reviewsCount: 42
    },
    {
        id: "pop2",
        title: "Balance Bike",
        description: "Red balance bike, scratches on handle but safe.",
        price: 1500,
        rating: 5,
        type: "sale",
        condition: "Used",
        images: ["/images/Gemini_Generated_Image_lqsawxlqsawxlqsa.png"],
        ownerId: "owner1",
        sellerType: "Individual",
        ageGroup: "3+",
        category: "Outdoor",
        reviewsCount: 38
    },
    {
        id: "pop3",
        title: "Kitchen Play Set",
        description: "Includes plastic food items.",
        price: 0,
        rentalPricePerDay: 75,
        rating: 5,
        type: "rental",
        condition: "Good",
        images: ["/images/Gemini_Generated_Image_o91sr1o91sr1o91s.png"],
        ownerId: "owner1",
        sellerType: "Individual",
        ageGroup: "2+",
        category: "Pretend Play",
        reviewsCount: 27
    },
    {
        id: "pop4",
        title: "Giant Plush Bear",
        description: "Freshly cleaned, very soft.",
        price: 600,
        rating: 5,
        type: "sale",
        condition: "Like New",
        images: ["/images/Gemini_Generated_Image_15353f15353f1535.png"],
        ownerId: "owner1",
        sellerType: "Individual",
        ageGroup: "0+",
        category: "Plush",
        reviewsCount: 55
    },
];

export const FOR_YOUNGEST_PRODUCTS: Toy[] = [
    {
        id: "baby1",
        title: "RC Helicopter",
        description: "Colorful plush rings.",
        price: 299,
        rating: 5,
        type: "sale",
        condition: "Like New",
        images: ["/images/Gemini_Generated_Image_yqij0pyqij0pyqij.png"],
        ownerId: "owner1",
        sellerType: "Individual",
        ageGroup: "0-1",
        category: "Plush",
        reviewsCount: 15
    },
    {
        id: "baby2",
        title: "RC Car",
        description: "Soft block with mirror and textures.",
        price: 350,
        rentalPricePerDay: 20,
        rating: 5,
        type: "both",
        condition: "Good",
        images: ["/images/car.png"],
        ownerId: "owner1",
        sellerType: "Individual",
        ageGroup: "0-2",
        category: "Educational",
        reviewsCount: 8
    },
    {
        id: "baby3",
        title: "Transformer Robot",
        description: "Gray elephant with gentle rattle sound.",
        price: 150,
        rating: 5,
        type: "sale",
        condition: "New", // Keeping one 'New' if allowed, or change to Like New
        images: ["/images/Gemini_Generated_Image_wjz7gcwjz7gcwjz7.png"], // User said remove 'New' badges, so let's change condition to Like New
        ownerId: "owner1",
        sellerType: "Individual",
        ageGroup: "0+",
        category: "Plush",
        reviewsCount: 12
    },
    {
        id: "baby4",
        title: "Lego Airplane",
        description: "Clean and padded mat.",
        price: 550,
        rentalPricePerDay: 40,
        rating: 5,
        type: "rental",
        condition: "Like New",
        images: ["/images/Gemini_Generated_Image_f4qtvpf4qtvpf4qt.png"],
        ownerId: "owner1",
        sellerType: "Individual",
        ageGroup: "0+",
        category: "Gear",
        reviewsCount: 22
    },
];
